### ISSUE TITLE
Import open issues from archived project

### ISSUE THREAD

**Issue by Teutenberg** [Teutenberg/DBAid2#1]
Download issue JSON from GitHub api:
https://api.github.com/repos/teutenberg/dbaid/issues?state=open

Can covert JSON to CSV if required: https://konklone.io/json/

Can use GitHub PowerShell module to import:
https://github.com/microsoft/PowerShellForGitHub

**Comment by thecosmictrickster** [comment]
Looking at all this, the JSON export doesn't capture comments and you'd still have to write a script to use the PowerShell module to import by reading from the JSON or CSV. For 11 issues, just as easy to [manually transfer](https://help.github.com/en/articles/transferring-an-issue-to-another-repository) (which I would have done in the time it took to research this other stuff but I don't have the option available, probably because it's not my repo)

**Comment by Teutenberg** [comment]
Accept invite to DBAid2, https://github.com/Teutenberg/DBAid2/invitations

**Comment by Teutenberg** [comment]
Found that you cannot transfer issues from archived repo. Un-archived DBAid repo and and can transfer manually now.
